In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
customer = pd.read_csv("A_customer.csv")
film = pd.read_csv("A_film_revenue.csv")
geo = pd.read_csv("A_geography.csv")
inventory = pd.read_csv("AAA.csv")
staff = pd.read_csv("A_staff.csv")
time = pd.read_csv("A_time_base.csv")
full_data = pd.read_csv("best.csv")

In [4]:
M1 = pd.merge(
    customer[["store_id","city_id","full_name", "country", "city", "total_amount_spent","total_number_of_rentals"]],
    staff[["store_id", "staff_id","staff_name"]],
    on = "store_id",
    how = "inner"
)
M1

,store_id,city_id,full_name,country,city,total_amount_spent,total_number_of_rentals,staff_id,staff_name
0,1,442,Eleanor Hunt,Runion,Saint-Denis,211.55,45,1,Mike Hillyer
1,2,101,Karl Seal,United States,Cape Coral,208.58,42,2,Jon Stephens
2,2,456,Marion Snyder,Brazil,Santa Brbara dOeste,194.61,39,2,Jon Stephens
3,2,29,Rhonda Kennedy,Netherlands,Apeldoorn,191.62,38,2,Jon Stephens
4,1,340,Clara Shaw,Belarus,Molodetno,189.60,40,1,Mike Hillyer
...,...,...,...,...,...,...,...,...,...
594,2,159,Tiffany Jordan,China,Enshi,49.88,12,2,Jon Stephens
595,2,516,Anthony Schwab,American Samoa,Tafuna,47.85,15,2,Jon Stephens
596,1,520,Caroline Bowman,United States,Tallahassee,37.87,13,1,Mike Hillyer
597,2,175,Leona Obrien,China,Fuzhou,32.90,10,2,Jon Stephens
598,1,97,Brian Wyman,Poland,Bydgoszcz,27.93,7,1,Mike Hillyer

In [5]:
M1 = M1.rename(
    columns={
        "full_name": "customer_name",
        "country": "customer_country",
        "city": "customer_city",
        "total_amount_spent": "amount_spent_by_customer",
        "total_number_of_rentals": "number_rent_by_customer"
    }
)

M1

,store_id,city_id,customer_name,customer_country,customer_city,amount_spent_by_customer,number_rent_by_customer,staff_id,staff_name
0,1,442,Eleanor Hunt,Runion,Saint-Denis,211.55,45,1,Mike Hillyer
1,2,101,Karl Seal,United States,Cape Coral,208.58,42,2,Jon Stephens
2,2,456,Marion Snyder,Brazil,Santa Brbara dOeste,194.61,39,2,Jon Stephens
3,2,29,Rhonda Kennedy,Netherlands,Apeldoorn,191.62,38,2,Jon Stephens
4,1,340,Clara Shaw,Belarus,Molodetno,189.60,40,1,Mike Hillyer
...,...,...,...,...,...,...,...,...,...
594,2,159,Tiffany Jordan,China,Enshi,49.88,12,2,Jon Stephens
595,2,516,Anthony Schwab,American Samoa,Tafuna,47.85,15,2,Jon Stephens
596,1,520,Caroline Bowman,United States,Tallahassee,37.87,13,1,Mike Hillyer
597,2,175,Leona Obrien,China,Fuzhou,32.90,10,2,Jon Stephens
598,1,97,Brian Wyman,Poland,Bydgoszcz,27.93,7,1,Mike Hillyer

In [6]:
geo.columns

Index(['country_id', 'city_id', 'country', 'city', 'total_rentals',
       'total_revenue', 'number_of_unique_customers',
       'most_popular_film_category'],
      dtype='str')

In [7]:
M1.columns

Index(['store_id', 'city_id', 'customer_name', 'customer_country',
       'customer_city', 'amount_spent_by_customer', 'number_rent_by_customer',
       'staff_id', 'staff_name'],
      dtype='str')

In [8]:
M2 = pd.merge(
    M1,
    geo[['city_id','total_revenue','most_popular_film_category']],
    on = "city_id",
    how = "inner"
)

M2

,store_id,city_id,customer_name,customer_country,customer_city,amount_spent_by_customer,number_rent_by_customer,staff_id,staff_name,total_revenue,most_popular_film_category
0,1,442,Eleanor Hunt,Runion,Saint-Denis,211.55,45,1,Mike Hillyer,211.55,Sci-Fi
1,2,101,Karl Seal,United States,Cape Coral,208.58,42,2,Jon Stephens,208.58,Animation
2,2,456,Marion Snyder,Brazil,Santa Brbara dOeste,194.61,39,2,Jon Stephens,194.61,Animation
3,2,29,Rhonda Kennedy,Netherlands,Apeldoorn,191.62,38,2,Jon Stephens,191.62,Games
4,1,340,Clara Shaw,Belarus,Molodetno,189.60,40,1,Mike Hillyer,189.60,Drama
...,...,...,...,...,...,...,...,...,...,...,...
594,2,159,Tiffany Jordan,China,Enshi,49.88,12,2,Jon Stephens,49.88,Animation
595,2,516,Anthony Schwab,American Samoa,Tafuna,47.85,15,2,Jon Stephens,47.85,Sports
596,1,520,Caroline Bowman,United States,Tallahassee,37.87,13,1,Mike Hillyer,37.87,Sci-Fi
597,2,175,Leona Obrien,China,Fuzhou,32.90,10,2,Jon Stephens,32.90,Animation
598,1,97,Brian Wyman,Poland,Bydgoszcz,27.93,7,1,Mike Hillyer,27.93,Action

In [9]:
M2 = M2.rename(
    columns={
        "total_revenue": "total_revenue_in_geo_area"
    }
)

M2

,store_id,city_id,customer_name,customer_country,customer_city,amount_spent_by_customer,number_rent_by_customer,staff_id,staff_name,total_revenue_in_geo_area,most_popular_film_category
0,1,442,Eleanor Hunt,Runion,Saint-Denis,211.55,45,1,Mike Hillyer,211.55,Sci-Fi
1,2,101,Karl Seal,United States,Cape Coral,208.58,42,2,Jon Stephens,208.58,Animation
2,2,456,Marion Snyder,Brazil,Santa Brbara dOeste,194.61,39,2,Jon Stephens,194.61,Animation
3,2,29,Rhonda Kennedy,Netherlands,Apeldoorn,191.62,38,2,Jon Stephens,191.62,Games
4,1,340,Clara Shaw,Belarus,Molodetno,189.60,40,1,Mike Hillyer,189.60,Drama
...,...,...,...,...,...,...,...,...,...,...,...
594,2,159,Tiffany Jordan,China,Enshi,49.88,12,2,Jon Stephens,49.88,Animation
595,2,516,Anthony Schwab,American Samoa,Tafuna,47.85,15,2,Jon Stephens,47.85,Sports
596,1,520,Caroline Bowman,United States,Tallahassee,37.87,13,1,Mike Hillyer,37.87,Sci-Fi
597,2,175,Leona Obrien,China,Fuzhou,32.90,10,2,Jon Stephens,32.90,Animation
598,1,97,Brian Wyman,Poland,Bydgoszcz,27.93,7,1,Mike Hillyer,27.93,Action

In [10]:
inventory.columns

Index(['store_id', 'film_id', 'category_id', 'film_title', 'category',
       'inventory_count', 'total_rentals', 'total_revenue', 'last_rental_date',
       'average_rental_duration_days'],
      dtype='str')

In [11]:
inventory.shape

(1563, 10)

In [12]:
film.columns

Index(['film_id', 'category_id', 'film_title', 'category', 'average_price',
       'quantity', 'total_rental_revenue', 'last_rental_date'],
      dtype='str')

In [13]:
film.shape

(1000, 8)

In [14]:
M3 = pd.merge(
    film[['film_id', 'category_id', 'film_title', 'category', 'average_price',
       'quantity', 'total_rental_revenue', 'last_rental_date']],
    inventory[['film_id','store_id', 'inventory_count',
       'total_rentals', 'total_revenue',
       'average_rental_duration_days']],
    on = "film_id",
    how = "inner"
)

M3

,film_id,category_id,film_title,category,average_price,quantity,total_rental_revenue,last_rental_date,store_id,inventory_count,total_rentals,total_revenue,average_rental_duration_days
0,1,6,Academy Dinosaur,Documentary,0.99,6,5.94,2006-02-15 10:07:09,1.0,4,12,18.89,5.00
1,1,6,Academy Dinosaur,Documentary,0.99,6,5.94,2006-02-15 10:07:09,2.0,4,11,14.90,4.99
2,2,11,Ace Goldfinger,Horror,4.99,3,14.97,2006-02-15 10:07:09,2.0,3,7,52.93,5.64
3,3,6,Adaptation Holes,Documentary,2.99,7,20.93,2006-02-15 10:07:09,2.0,4,12,34.89,3.47
4,4,11,Affair Prejudice,Horror,2.99,5,14.95,2006-02-15 10:07:09,1.0,4,13,49.88,5.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,998,11,Zhivago Core,Horror,0.99,6,5.94,2006-02-15 10:07:09,2.0,2,9,10.93,5.95
1559,999,3,Zoolander Fiction,Children,2.99,5,14.95,2006-02-15 10:07:09,2.0,3,11,42.91,5.49
1560,999,3,Zoolander Fiction,Children,2.99,5,14.95,2006-02-15 10:07:09,1.0,2,6,23.94,5.64
1561,1000,5,Zorro Ark,Comedy,4.99,3,14.97,2006-02-15 10:07:09,1.0,4,16,108.85,4.85
1562,1000,5,Zorro Ark,Comedy,4.99,3,14.97,2006-02-15 10:07:09,2.0,4,15,90.87,4.20